name: CI-MISC
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.package }} - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1' # LTS
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        package: # only test Yao and YaoBlocks on LTS
          - Yao
          - YaoBlocks
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - name: "develop lib packages"
        run: julia --project .ci/run.jl dev
      - uses: julia-actions/julia-buildpkg@v1
      - name: "run tests"
        run: julia --project .ci/run.jl test ${{ matrix.package }}
