name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: setup non-registered dependencies
        run: |
          using Pkg
          Pkg.add(PackageSpec(url="https://github.com/QuantumBFS/QuAlgorithmZoo.jl.git"))
          Pkg.develop(PackageSpec(path=pwd()))
        shell: julia --project=docs --color=yes {0}
      - name: Install dependencies
        run: julia --project=docs/ .ci/run.jl doc
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: GKSwstype=100 julia --project=docs/ docs/make.jl
